### ISSUE TITLE
Additional parent info request

### ISSUE THREAD

**Issue by eberhardtm** [AppStateESS/conference#23]
I am setting up an api endpoint for James Hayes to provide parent orientation data. He is requesting to add relationship(mother,father,etc) and optional fields for work information(employer and job title).

**Comment by eberhardtm** [comment]
We would want to track the visitor relation as well as the guest relation

**Comment by eberhardtm** [comment]
They would also like to request adding cell phone number field to the registrant form.

**Comment by eberhardtm** [comment]
You can also reference this jira ticket. https://jira.appstate.edu/browse/ATSD-57361

**Comment by Stardog** [comment]
Remove conference questions.
